apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: store-service

build:
  artifacts:
    - image: asia-southeast2-docker.pkg.dev/project-fc5426d4-53ee-47af-8fb/development/store-service
      docker:
        dockerfile: Dockerfile
  local:
    push: true

manifests:
  rawYaml:
    - kube/k8s-dev.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: Service
    resourceName: store-service
    namespace: sol-scale-dev
    port: 3000
    localPort: 8000
