type Job {
  id: Int
  entrepreneurId: Int
  title: String
  description: String
  brief: String
  platform: String
  deliverables: [String!]
  requirements: [String!]
  tags: [String!]
  location: String
  duration: String
  budgetMin: Int
  budgetMax: Int
  startAt: DateTime
  endAt: DateTime
  status: String
  promoted: Boolean
  createdAt: DateTime
  updatedAt: DateTime
  entrepreneur: Entrepreneur
}

type JobPayload {
  data: Job
  status: StatusPayload
}

type JobsPayload {
  data: [Job]
  status: StatusPayload
}

input CreateJobInput {
  title: String!
  description: String!
  brief: String
  platform: String!
  deliverables: [String!]
  requirements: [String!]
  tags: [String!]
  location: String
  duration: String
  budgetMin: Int
  budgetMax: Int
  startAt: DateTime
  endAt: DateTime
}

input UpdateJobInput {
  id: Int!
  title: String
  description: String
  brief: String
  platform: String
  deliverables: [String!]
  requirements: [String!]
  tags: [String!]
  location: String
  duration: String
  budgetMin: Int
  budgetMax: Int
  startAt: DateTime
  endAt: DateTime
  status: String
}

input JobFilterInput {
  platforms: [String!]
  tags: [String!]
  location: String
  budgetMin: Int
  budgetMax: Int
}

type Query {
  jobs(limit: Int, offset: Int, search: String, filter: JobFilterInput): JobsPayload
  job(id: Int!): JobPayload
  myJobs: JobsPayload
}

type Mutation {
  createJob(input: CreateJobInput!): JobPayload
  updateJob(input: UpdateJobInput!): JobPayload
}
